### ISSUE TITLE
Опечатки.

### ISSUE THREAD

**Issue by andrey-ilyin** [orazaev-sergej/Backend#1]
https://github.com/orazaev-sergej/Backend/blob/5b9c35c566984513a9c70567f3cf373d7efc474c/lab0/1.txt#L1

**Comment by orazaev-sergej** [comment]
исправил

**Comment by orazaev-sergej** [comment]
D0 BE D1 80 D0 B0 D0 B7 D0 B0 D0 B5 D0 B2 20 D1 81 D0 B5 D1 80 D0 B3 D0 B5 D0 B9
