### ISSUE TITLE
Дополните.

### ISSUE THREAD

**Issue by andrey-ilyin** [orazaev-sergej/Backend#2]
https://github.com/orazaev-sergej/Backend/blob/5b9c35c566984513a9c70567f3cf373d7efc474c/lab1/3.txt#L6

* Какая кодировка файла?
* Как определили?
* Напишите 3 способа сообщить браузеру верную кодировку.

**Comment by orazaev-sergej** [comment]
Кодировка файла "windows-1251"

С помощью команды "document.characterSet" в консоли

1. В HTML-документе добавить `<meta charset="utf-8">` в контейнер head.
2. В самом браузере выбрать кодировку страницы.
3. В настройках сервера. Открыть или создать файл .htaccess и
     прописать строку "AddDefaultCharset UTF-8"
